# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Friday_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Friday(object):
    def setupUi(self, Friday):
        Friday.setObjectName("Friday")
        Friday.resize(1171, 600)
        self.centralwidget = QtWidgets.QWidget(Friday)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(700, 0, 471, 301))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Iron_Template_1.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(706, 302, 471, 301))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("B.G_Template_1.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 541, 271))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("initial.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 410, 351, 191))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Jarvis_Gui (1).gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(390, 510, 141, 61))
        self.pushButton.setStyleSheet("background-color: rgb(77, 232, 232);\n"
"border-color: rgb(85, 170, 255);\n"
"font: 20pt \"Rockwell\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 510, 141, 61))
        self.pushButton_2.setStyleSheet("background-color: rgb(77, 232, 232);\n"
"border-color: rgb(85, 170, 255);\n"
"font: 20pt \"Rockwell\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(-140, -10, 1231, 681))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Black_Template.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(-4, 182, 341, 241))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Siri_1.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_5.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_6.raise_()
        Friday.setCentralWidget(self.centralwidget)

        self.retranslateUi(Friday)
        QtCore.QMetaObject.connectSlotsByName(Friday)

    def retranslateUi(self, Friday):
        _translate = QtCore.QCoreApplication.translate
        Friday.setWindowTitle(_translate("Friday", "MainWindow"))
        self.pushButton.setText(_translate("Friday", "START"))
        self.pushButton_2.setText(_translate("Friday", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Friday = QtWidgets.QMainWindow()
    ui = Ui_Friday()
    ui.setupUi(Friday)
    Friday.show()
    sys.exit(app.exec_())
